#!/usr/bin/env python3
"""Cache-identity tests for the Assist orchestrator (audit finding B8).

`run_assist`'s entire reuse decision is one function, `_cache_matches`, and it
had no test call site at all. The 2026-08-29 assist audit
(`docs/archive/ASSIST_AUDIT_2026-08-29.md`, B8) gutted it twice and watched the
whole Python suite stay green:

- dropping the `accept=` predicate, so an artifact produced by a *different
  model or route* is reused -- §5 rule 7 gone;
- dropping the `audio.sha256` comparison, so track B reuses track A's
  transcript.

Every test in `CacheIdentityTests` below fails under one of those two, which is
the negative control this file exists to satisfy. The artifacts are written to
a real temporary file rather than passed as dicts, because the on-disk read and
the `normalized` envelope unwrap are part of what is being pinned.

`XdgCacheDirectoryTests` covers finding B12's Python half. It lives here rather
than beside `AtomicCacheTests` in `tests/test_provider_discovery.py` only
because that file was being edited in parallel when this one was written.
"""

from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

import atomic_cache  # noqa: E402
import external_analysis  # noqa: E402


AUDIO_A = "a" * 64
AUDIO_B = "b" * 64
WHISPER_SCHEMA = "musializer.lyric-timing/v1"


def coarse_snapshot(**row_overrides: object) -> dict[str, object]:
    """A `musializer.assist-execution/v1` record carrying one TC-COARSE route.

    Hand-written on the reader's side, for the reason
    `tests/test_assist_execution.py` gives: a fixture generated by the writer
    could hide the disagreement these tests exist to catch.
    """
    row: dict[str, object] = {
        "contract": "TC-COARSE", "route_type": "local-proc",
        "runtime_id": "whisper-cpp", "runtime_version": None,
        "model_id": "ggml-large-v3.bin", "model_sha256": None,
        "reasoning_effort": None, "boundary_applied": "local-only",
        "boundary_confirmed": False, "audio_scope": "whole-track",
        "excerpt_spans": [], "provider_constraints": None,
        "provider_served": None, "prompt_version": None,
        "prompt_sha256": None, "schema_version": None,
        "fallback_policy": "none", "fallback_taken": False,
        "fallback_from": None,
    }
    row.update(row_overrides)
    return {
        "snapshot_schema": "musializer.assist-execution/v1",
        "settings_schema": "musializer.assist-settings/v1",
        "profile_id": "studio",
        "resolved_at_utc": "2026-08-29T12:00:00Z",
        "contracts": [row],
        "catalog_revision": None,
        "suitability_revision": None,
        "credential_present": False,
        "credential_fingerprint": None,
    }


def whisper_artifact(*, audio_sha: str, identity: dict[str, object] | None,
                     schema_version: str = WHISPER_SCHEMA) -> dict[str, object]:
    """A coarse-lane document `_whisper_cache_accepts` accepts when it matches."""
    document: dict[str, object] = {
        "schema_version": schema_version,
        "lane": "lyric_sync",
        "audio": {"sha256": audio_sha, "duration_seconds": 212.5},
        "provenance": {
            "adapter": "tools/external_analysis.py",
            "adapter_version": external_analysis.ADAPTER_VERSION,
            "source_kind": "whisper_import",
            "model": "ggml-large-v3.bin",
            "request_settings": {
                "language": "en", "gpu_requested": True,
                "model_sha256": "9" * 64,
            },
        },
        "lines": [],
    }
    if identity is not None:
        provenance = document["provenance"]
        assert isinstance(provenance, dict)
        provenance["execution"] = {"route_identity": identity}
    return document


class CacheIdentityTests(unittest.TestCase):
    """`_cache_matches` is the whole of the orchestrator's reuse decision."""

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.path = Path(self._tmp.name) / "lyrics.json"

    def write(self, document: dict[str, object]) -> None:
        self.path.write_text(json.dumps(document), encoding="utf-8")

    def identity(self, **row_overrides: object) -> dict[str, object]:
        resolved = external_analysis.route_identity(
            coarse_snapshot(**row_overrides), "TC-COARSE")
        assert resolved is not None
        return resolved

    def accepts(self, identity: dict[str, object] | None):
        return lambda value: external_analysis._whisper_cache_accepts(
            value, measured_duration=212.5, model=None,
            execution_route=identity)

    def match(self, *, audio_sha: str = AUDIO_A,
              schema_version: str = WHISPER_SCHEMA,
              identity: dict[str, object] | None = None):
        return external_analysis._cache_matches(
            self.path, schema_version, audio_sha,
            accept=self.accepts(identity))

    # -- the artifact that is genuinely this run's ------------------------

    def test_the_same_track_on_the_same_route_is_reused(self) -> None:
        identity = self.identity()
        self.write(whisper_artifact(audio_sha=AUDIO_A, identity=identity))
        reused = self.match(identity=identity)
        self.assertIsNotNone(reused)
        assert reused is not None
        self.assertEqual(reused["audio"]["sha256"], AUDIO_A)

    # -- accept=: a different model or route is a different artifact ------
    #
    # These three fail if `_cache_matches` stops calling `accept`.

    def test_a_different_model_on_the_same_contract_is_regenerated(self) -> None:
        self.write(whisper_artifact(
            audio_sha=AUDIO_A, identity=self.identity(model_id="ggml-medium.bin")))
        self.assertIsNone(self.match(identity=self.identity()))

    def test_a_different_route_type_is_regenerated(self) -> None:
        self.write(whisper_artifact(
            audio_sha=AUDIO_A, identity=self.identity(route_type="openrouter",
                                                      runtime_id="openrouter")))
        self.assertIsNone(self.match(identity=self.identity()))

    def test_an_artifact_with_no_recorded_route_is_regenerated(self) -> None:
        """An unknown route is not a matching route (§5 rule 7)."""
        self.write(whisper_artifact(audio_sha=AUDIO_A, identity=None))
        self.assertIsNone(self.match(identity=self.identity()))

    def test_an_unrouted_run_still_checks_the_rest_of_the_predicate(self) -> None:
        """`identity is None` waives the route clause, not the whole accept."""
        document = whisper_artifact(audio_sha=AUDIO_A, identity=None)
        provenance = document["provenance"]
        assert isinstance(provenance, dict)
        provenance["source_kind"] = "manual_import"
        self.write(document)
        self.assertIsNone(self.match(identity=None))

    # -- audio.sha256: track B must not reuse track A's transcript --------
    #
    # These two fail if the digest comparison is dropped.

    def test_a_different_track_is_regenerated(self) -> None:
        identity = self.identity()
        self.write(whisper_artifact(audio_sha=AUDIO_B, identity=identity))
        self.assertIsNone(self.match(audio_sha=AUDIO_A, identity=identity))

    def test_the_digest_is_read_through_the_normalized_envelope(self) -> None:
        """`musializer.analysis-cache/v1` wraps its document one level down.

        The envelope branch has its own `document =` expression, so a digest
        check that only worked on the flat shape would leave this lane reusing
        another track's cache while every other lane refused.
        """
        envelope_schema = "musializer.analysis-cache/v1"
        self.write({
            "schema_version": envelope_schema,
            "normalized": {"audio": {"sha256": AUDIO_B}},
        })
        self.assertIsNone(external_analysis._cache_matches(
            self.path, envelope_schema, AUDIO_A))
        self.write({
            "schema_version": envelope_schema,
            "normalized": {"audio": {"sha256": AUDIO_A}},
        })
        self.assertIsNotNone(external_analysis._cache_matches(
            self.path, envelope_schema, AUDIO_A))

    # -- schema_version: a format change forces regeneration --------------

    def test_an_older_schema_version_is_regenerated(self) -> None:
        identity = self.identity()
        self.write(whisper_artifact(
            audio_sha=AUDIO_A, identity=identity,
            schema_version="musializer.lyric-timing/v0"))
        self.assertIsNone(self.match(identity=identity))

    # -- the file itself --------------------------------------------------

    def test_an_absent_cache_is_not_an_error(self) -> None:
        self.assertIsNone(self.match(identity=self.identity()))

    def test_a_corrupt_cache_is_not_an_error(self) -> None:
        self.path.write_text("{ truncated", encoding="utf-8")
        self.assertIsNone(self.match(identity=self.identity()))


class RouteIdentityTests(unittest.TestCase):
    """What `route_identity` puts in the key the artifacts are compared on."""

    def test_the_identity_is_exactly_the_declared_fields(self) -> None:
        identity = external_analysis.route_identity(
            coarse_snapshot(), "TC-COARSE")
        assert identity is not None
        self.assertEqual(tuple(identity),
                         external_analysis.EXECUTION_ROUTE_IDENTITY_FIELDS)

    def test_a_field_outside_the_identity_does_not_force_regeneration(self) -> None:
        """`fallback_taken` is an outcome, not a route: it must not be a key."""
        recorded = external_analysis.route_identity(
            coarse_snapshot(fallback_taken=True), "TC-COARSE")
        self.assertEqual(recorded,
                         external_analysis.route_identity(coarse_snapshot(),
                                                          "TC-COARSE"))

    def test_a_contract_the_run_did_not_compose_has_no_identity(self) -> None:
        self.assertIsNone(external_analysis.route_identity(
            coarse_snapshot(), "TC-SEMANTIC"))

    def test_an_unrouted_run_has_no_identity(self) -> None:
        self.assertIsNone(external_analysis.route_identity(None, "TC-COARSE"))

    def test_an_unrouted_run_accepts_an_artifact_with_no_route(self) -> None:
        self.assertTrue(external_analysis._execution_route_accepts({}, None))


class XdgCacheDirectoryTests(unittest.TestCase):
    """Finding B12: the cache directory must resolve the same in both languages.

    The XDG base directory spec says a non-absolute value in `XDG_CACHE_HOME`
    is invalid and must be ignored. There were three copies of this rule and
    they had drifted: Python expanded `~` where the two Rust copies took it
    literally, so `XDG_CACHE_HOME="~/c"` named two different directories --
    Python's expanded home, Rust's literal `~/c` relative to whatever the
    process's working directory happened to be. Ignoring it is the answer that
    is both spec-correct and reachable from Rust.

    Rust is now one function,
    `musializer-runtime/src/assist/files.rs::cache_dir` (the two former copies
    call it), pinned by
    `a_non_absolute_xdg_cache_home_is_ignored_rather_than_resolved` over the
    same vectors as below.
    """

    def test_an_absolute_value_is_used(self) -> None:
        self.assertEqual(
            atomic_cache.cache_dir({"XDG_CACHE_HOME": "/tmp/xdg-example"}),
            Path("/tmp/xdg-example/musializer"))

    def test_a_tilde_is_not_expanded_but_ignored(self) -> None:
        self.assertEqual(atomic_cache.cache_dir({"XDG_CACHE_HOME": "~/c"}),
                         Path.home() / ".cache/musializer")

    def test_a_relative_value_is_ignored(self) -> None:
        self.assertEqual(atomic_cache.cache_dir({"XDG_CACHE_HOME": "cache"}),
                         Path.home() / ".cache/musializer")

    def test_a_value_that_is_absolute_only_after_stripping_is_ignored(self) -> None:
        """Rust would take the leading space literally; so must Python."""
        self.assertEqual(atomic_cache.cache_dir({"XDG_CACHE_HOME": " /tmp/x"}),
                         Path.home() / ".cache/musializer")

    def test_an_empty_value_falls_back(self) -> None:
        self.assertEqual(atomic_cache.cache_dir({"XDG_CACHE_HOME": ""}),
                         Path.home() / ".cache/musializer")

    def test_an_absent_value_falls_back(self) -> None:
        self.assertEqual(atomic_cache.cache_dir({}),
                         Path.home() / ".cache/musializer")


if __name__ == "__main__":
    unittest.main()
