/*
 * Differential harness: dumps the *oracle's* beat tracker over a grid of tick
 * rates and onset patterns plus a set of hand-built boundary cases, so the Rust
 * port can be compared against it numerically instead of against a table of
 * numbers somebody typed in.
 *
 * This compiles `../musializer/src/beat_tracker.c` from the frozen C repository
 * unmodified. It reads that tree and writes only into our own `build/`; the
 * oracle is never modified, and its own build directory is never touched.
 *
 * Why this module gets a harness. Two reasons, and the second is the sharper one:
 *
 *   - It feeds a documented route source. `--route parameter:beat_phase:...` is
 *     part of the CLI grammar, so the phase this produces is observable in a
 *     rendered MP4 and therefore parity-relevant rather than internal.
 *   - The port's strongest existing evidence was a *hand-transcribed* table:
 *     `matches_the_c_oracle_step_for_step` pastes eight `%.9g` phases captured
 *     from a scratch C build that no longer exists. That is precisely the shape
 *     this project has written a rule against -- a typo makes it wrong forever,
 *     and a number accidentally copied from our own output makes it tautological
 *     forever. It cannot be re-derived without redoing the work by hand. This
 *     harness re-derives it on every run, from the oracle, at 8 values -> ~123000.
 *
 * The remaining assertions in the port are mostly ranges (`interval > 0.55 &&
 * interval < 0.60`, `phase > 0.25 && phase < 0.28`), inherited from
 * `../musializer/tests/test_beat_tracker.c`, which pins 7 values out of 18
 * expectations and gives every float a 1e-6 tolerance. A range is satisfied by a
 * wrong formula; see AGENTS.md's measured table.
 *
 * What is compared, and why that is the whole observable surface. `Beat_Tracker`
 * has seven fields; the Rust port exposes three of them (`interval_seconds`,
 * `learned_intervals`, `has_onset`) plus the phase and the accept/reject
 * decision. The other four are pinned *behaviourally* rather than by reading them
 * out, because each has an effect that surfaces within one or two steps and the
 * cases below are built to force it:
 *
 *   - `anchor_time`   -> the phase, on every single row.
 *   - `previous_time` -> the restart decision on the next row, which moves the
 *                        anchor and so moves the phase. `restart_boundary` steps
 *                        across the 0.75 s threshold exactly.
 *   - `last_onset_time` -> whether an inter-onset gap is credible, which moves
 *                        `learned_intervals`. The four `gap_*` cases straddle both
 *                        ends of [0.25, 1.5] by one double.
 *   - `initialized`   -> the first row of every case.
 *
 * Adding accessors to the port purely so a test could read them would widen the
 * public API to check something the public API already reveals.
 *
 * Everything printed here is generated by plain double arithmetic with explicit
 * evaluation order, duplicated in `beat_tracker_dump.rs` on purpose. Two copies of
 * a generator is normally a smell; here it is the entire mechanism, because a
 * shared generator could hide the very difference the test looks for. The grid
 * *inputs* are printed alongside the outputs so the two generators are themselves
 * compared: if they ever drift apart, the input columns fail before the value
 * columns do.
 *
 * Build and run through tools/differential_beat_tracker.sh.
 */

#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>

#include "beat_tracker.h"

/*
 * Seventeen digits after the point, in exponential form. A double round-trips in
 * seventeen significant digits, so printing is not the limiting factor and any
 * delta the comparison reports is arithmetic rather than formatting. Exponential
 * form also keeps a float token from ever looking like an integer to the
 * comparison script, which is how it knows which columns to compare exactly.
 *
 * Non-finite values get a *label* instead of `nan`/`inf`. That is not cosmetic:
 * `nan` and `inf` both parse as floats in Python, and `abs(nan - nan) > tol` is
 * False, so a column of them would pass unconditionally -- a silent hole this
 * project has already been bitten by once. These labels contain no digits and no
 * spelling `float()` accepts, so they fall through to the exact-string branch and
 * a NaN where a number belongs fails loudly. It matters here more than in most of
 * these harnesses, because feeding NaN in is a case rather than an accident.
 */
#define FLOAT_FMT "%.17e"

/*
 * A rotating pool so several numbers can appear in one printf. Argument
 * evaluation order is unspecified in C, which is exactly why each call must get
 * its own buffer rather than share one; no record below prints more than four
 * numbers.
 */
#define NUM_BUF_COUNT 8
static char num_bufs[NUM_BUF_COUNT][48];
static int num_buf_next = 0;

static const char *num(double value)
{
    if (isnan(value)) return "not_a_number";
    if (isinf(value)) return value > 0.0 ? "positive_infinity" : "negative_infinity";
    char *buf = num_bufs[num_buf_next];
    num_buf_next = (num_buf_next + 1)%NUM_BUF_COUNT;
    snprintf(buf, sizeof num_bufs[0], FLOAT_FMT, value);
    return buf;
}

/*
 * One update, and everything a caller can see afterwards.
 *
 * The outcome column has three values, not two, and separating them is what this
 * harness found a parity bug with. `beat_tracker_update` returns false in two
 * unrelated situations:
 *
 *   - it refused the input, and returned *before* writing the out-parameter;
 *   - it computed a position inside [0, 1), narrowed it to a float that landed on
 *     exactly 1.0, wrote that, and refused it afterwards (`beat_tracker.c:76-78`).
 *
 * `plug.c:1139-1144` cannot tell those apart either -- it keeps a local
 * initialised to 0.0f, passes its address, and uses whatever is in it. So the
 * observable result differs: 0.0 in the first case and 1.0 in the second, both
 * copied into the scene frame at `plug.c:1157` and `plug.c:1185`. The Rust port
 * originally returned `None` for both and lost the distinction.
 *
 * Seeding with -1.0f is how this harness tells them apart, and it is the same
 * mechanism plug.c uses, just with a sentinel a phase can never be: `position` is
 * pushed non-negative before the narrowing (`beat_tracker.c:73-74`), so a written
 * value is always >= 0 and an untouched -1.0f means the oracle never wrote.
 */
static void step(Beat_Tracker *tracker, const char *name, int index,
                 double time, bool onset, float strength)
{
    const float sentinel = -1.0f;
    float phase = sentinel;
    bool accepted = beat_tracker_update(tracker, time, onset, strength, &phase);
    const char *outcome = accepted ? "phase"
                        : phase != sentinel ? "out_of_range"
                        : "refused";
    printf("step %s %d %s %d %s %s %s %s %zu %d\n",
           name, index,
           num(time), onset ? 1 : 0, num((double)strength),
           outcome,
           accepted || phase != sentinel ? num((double)phase) : "not_reported",
           num(tracker->interval_seconds), tracker->learned_intervals,
           tracker->has_onset ? 1 : 0);
}

static void dump_reset(Beat_Tracker *tracker, const char *name, int index)
{
    beat_tracker_reset(tracker);
    printf("reset %s %d %s %zu %d\n", name, index,
           num(tracker->interval_seconds), tracker->learned_intervals,
           tracker->has_onset ? 1 : 0);
}

/* ------------------------------------------------------------------------- *
 * The grid. Duplicated in beat_tracker_dump.rs, value for value.
 * ------------------------------------------------------------------------- */

/*
 * Tick rates from a 5 ms analysis hop up to 0.8 s -- the last one is past the
 * 0.75 s discontinuity threshold, so that whole row of the grid restarts on
 * *every* step and never learns anything. That is a real state the frame loop can
 * reach on a stalled preview, and it is the one where a sign or comparison slip
 * hides, because the tracker still returns a plausible phase throughout.
 */
static const double TICKS[] = { 0.005, 1.0/60.0, 0.02, 0.037, 0.25, 0.3, 0.8 };
#define TICK_COUNT ((int)(sizeof TICKS/sizeof TICKS[0]))

/* 0 means "never fires". Period 1 means every step, which for the fast ticks is
 * a stream of sub-minimum gaps that must all be refused as observations. */
static const int ONSET_PERIODS[] = { 0, 1, 3, 8, 12, 24, 30 };
#define PERIOD_COUNT ((int)(sizeof ONSET_PERIODS/sizeof ONSET_PERIODS[0]))

/*
 * Chosen to straddle the 0.04 noise floor from both sides by one representable
 * step, and to include a value far above anything an onset detector produces --
 * the tracker only ever compares strength against the floor, and a harness that
 * never says so cannot notice if that changes.
 */
static const float STRENGTHS[] = { 0.0f, 0.039f, 0.04f, 0.125f, 0.5f, 0.75f, 1.0f, 4.0f };
#define STRENGTH_COUNT ((int)(sizeof STRENGTHS/sizeof STRENGTHS[0]))

/* Applied once per sequence, after the tick, to force a discontinuity mid-run.
 * The negative one drives time below zero for a few steps, so the rejection path
 * is exercised inside a running sequence and not only from a fresh tracker. */
static const double JUMPS[] = { 0.75, 0.7500000001, 5.0, -0.5 };
#define JUMP_COUNT ((int)(sizeof JUMPS/sizeof JUMPS[0]))

#define GRID_STEPS 250

/*
 * A 64-bit LCG, in integer arithmetic only, so the two sides cannot disagree
 * about the strength schedule for a floating-point reason. The constants are
 * Knuth's MMIX pair; nothing here needs a good generator, only an identical one.
 */
static unsigned long long lcg_next(unsigned long long *state)
{
    *state = *state*6364136223846793005ULL + 1442695040888963407ULL;
    return *state >> 33;
}

static void run_grid(void)
{
    for (int ti = 0; ti < TICK_COUNT; ++ti) {
        for (int pi = 0; pi < PERIOD_COUNT; ++pi) {
            int seq = ti*PERIOD_COUNT + pi;
            char name[32];
            snprintf(name, sizeof name, "grid_%d_%d", ti, pi);

            Beat_Tracker tracker;
            beat_tracker_reset(&tracker);

            unsigned long long lcg = 1ULL + (unsigned long long)seq*2654435761ULL;
            double time = 0.0;
            int seek_step = 60 + (7*seq)%130;
            double jump = JUMPS[(ti + pi)%JUMP_COUNT];

            for (int index = 0; index < GRID_STEPS; ++index) {
                /* Drawn unconditionally so the two streams stay aligned even
                 * where the value is unused. */
                float strength = STRENGTHS[lcg_next(&lcg)%STRENGTH_COUNT];
                bool onset = ONSET_PERIODS[pi] != 0 && index%ONSET_PERIODS[pi] == 0;
                step(&tracker, name, index, time, onset, strength);
                time += TICKS[ti];
                if (index == seek_step) time += jump;
            }
        }
    }
}

/* ------------------------------------------------------------------------- *
 * Boundary cases. Literal times throughout -- no arithmetic at all -- so that
 * "exactly 0.75" means the double nearest 0.75 on both sides rather than
 * whatever an accumulator happened to land on.
 * ------------------------------------------------------------------------- */

typedef struct {
    double time;
    int onset;
    float strength;
} Input;

static void run_case(const char *name, const Input *inputs, size_t count)
{
    Beat_Tracker tracker;
    beat_tracker_reset(&tracker);
    for (size_t i = 0; i < count; ++i) {
        step(&tracker, name, (int)i, inputs[i].time, inputs[i].onset != 0,
             inputs[i].strength);
    }
}

/* The restart test is `> 0.75`, so a gap of exactly 0.75 must NOT restart. One
 * double above it must. Nothing in either test suite uses a 0.75 gap, which is
 * why this case exists. */
static const Input RESTART_BOUNDARY[] = {
    { 0.0,            0, 0.0f },
    { 0.75,           0, 0.0f },
    { 1.5,            0, 0.0f },
    { 2.2500000001,   0, 0.0f },
    { 3.0,            0, 0.0f },
    { 3.75,           0, 0.0f },
    { 4.5000000000001, 0, 0.0f },
};

/* An inter-onset gap of exactly 0.25 s is credible (`>= minimum_interval`); one
 * double below is not. Both are reachable only because the tracker is being
 * ticked in between, which keeps previous_time close enough to avoid a restart. */
static const Input GAP_MIN_BOUNDARY[] = {
    { 0.0,                0, 0.0f },
    { 0.0,                1, 0.5f },
    { 0.125,              0, 0.0f },
    { 0.25,               1, 0.5f },
    { 0.375,              0, 0.0f },
    { 0.5,                1, 0.5f },
    { 0.625,              0, 0.0f },
    { 0.7499999999999999, 1, 0.5f },
    { 0.875,              0, 0.0f },
    { 1.0,                1, 0.5f },
};

/* An inter-onset gap of exactly 1.5 s is credible (`<= maximum_interval`); one
 * double above is refused *entirely* -- it must not even move the anchor, so the
 * phase keeps running off the previous anchor. That "ignored, not clamped"
 * behaviour is the easiest thing in this module to get wrong.
 *
 * The digits on the last onset are the case rather than noise: 4.5 plus one ULP,
 * which puts the gap from the onset at 3.0 one hair over the limit. */
static const Input GAP_MAX_BOUNDARY[] = {
    { 0.0,                1, 0.5f },
    { 0.5,                0, 0.0f },
    { 1.0,                0, 0.0f },
    { 1.5,                1, 0.5f },
    { 2.0,                0, 0.0f },
    { 2.5,                0, 0.0f },
    { 3.0,                1, 0.5f },
    { 3.5,                0, 0.0f },
    { 4.0,                0, 0.0f },
    { 4.5000000000000009, 1, 0.5f },
    { 5.0,                0, 0.0f },
    { 5.5,                0, 0.0f },
};

/*
 * 0.04 is the floor and counts; the nearest float below it does not, and an onset
 * flag with a sub-floor strength must leave has_onset alone. -0.0f is here because
 * `strength < 0.0f` is false for it in both languages, so it is accepted as a zero
 * rather than rejected as a negative -- an untested sign convention is where a
 * difference hides.
 *
 * This case is a function rather than a table because the value just below the
 * floor has to come from `nextafterf`, which is not a constant expression. Writing
 * it as a decimal does not work: `0.0399999991f` rounds back *to* 0.04f and
 * silently duplicates the row above it, so the boundary would look tested and not
 * be. The Rust side gets the identical value from the bit pattern, where it *can*
 * be a constant.
 */
static void run_strength_floor(void)
{
    const float just_below = nextafterf(0.04f, 0.0f);
    Beat_Tracker tracker;
    beat_tracker_reset(&tracker);
    int i = 0;
    step(&tracker, "strength_floor", i++, 0.0,  true,  0.0f);
    step(&tracker, "strength_floor", i++, 0.1,  true,  -0.0f);
    step(&tracker, "strength_floor", i++, 0.2,  true,  0.039f);
    step(&tracker, "strength_floor", i++, 0.3,  true,  just_below);
    step(&tracker, "strength_floor", i++, 0.4,  true,  0.04f);
    step(&tracker, "strength_floor", i++, 0.5,  false, 0.0f);
    step(&tracker, "strength_floor", i++, 0.65, true,  just_below);
    step(&tracker, "strength_floor", i++, 0.8,  true,  0.04f);
    step(&tracker, "strength_floor", i++, 0.9,  false, 0.0f);
    step(&tracker, "strength_floor", i++, 1.05, true,  1.0f);
}

/* Drives the estimate towards 0.6 s, then feeds a half-interval and a
 * double-interval observation. Both must fold into agreement rather than halving
 * or doubling the reported tempo, and folding must refuse to leave [0.25, 1.5]
 * rather than producing an absurd one. */
static const Input TEMPO_FOLD[] = {
    { 0.0,  1, 0.5f },
    { 0.3,  0, 0.0f },
    { 0.6,  1, 0.5f },
    { 0.9,  0, 0.0f },
    { 1.2,  1, 0.5f },
    { 1.5,  0, 0.0f },
    { 1.8,  1, 0.5f },
    { 2.1,  0, 0.0f },
    { 2.4,  1, 0.5f },
    { 2.7,  0, 0.0f },
    { 3.0,  1, 0.5f },
    { 3.3,  0, 0.0f },
    { 3.6,  1, 0.5f },
    { 3.9,  0, 0.0f },
    /* half the running estimate: folds up */
    { 4.2,  0, 0.0f },
    { 4.5,  1, 0.5f },
    { 4.8,  0, 0.0f },
    /* roughly double: folds down */
    { 5.4,  1, 0.5f },
    { 5.7,  0, 0.0f },
    { 6.0,  0, 0.0f },
    { 6.6,  1, 0.5f },
    { 6.9,  0, 0.0f },
};

/* Five exact 0.5 s gaps take learned_intervals from 0 through 5, so the blend
 * weight changes from 0.42 to 0.20 in the middle of one case and the 0.7 s
 * outlier at the end is absorbed by whichever weight is then current. Two
 * separate primings would let a wrong threshold pass by being wrong twice. */
static const Input WEIGHT_TRANSITION[] = {
    { 0.0, 1, 0.5f },
    { 0.5, 1, 0.5f },
    { 1.0, 1, 0.5f },
    { 1.5, 1, 0.5f },
    { 2.0, 1, 0.5f },
    { 2.5, 1, 0.5f },
    { 3.0, 1, 0.5f },
    { 3.7, 1, 0.5f },
    { 4.2, 1, 0.5f },
    { 4.7, 1, 0.5f },
};

/*
 * Every input the tracker refuses, from a fresh tracker and then from a running
 * one, followed by a valid call proving the refusals left no residue.
 *
 * The huge finite time is not padding: 1e18/0.5 is a whole double, so the
 * fractional part is exactly zero and the phase reads 0 -- and the next small
 * time is then a backwards jump, which restarts. A tracker that survived a
 * seek to the end of a 30-year track is worth one row.
 */
static void run_rejections(void)
{
    static const Input FRESH[] = {
        { -1.0,      0, 0.0f },
        { -0.0,      0, 0.0f },   /* not negative: accepted */
    };
    run_case("reject_fresh", FRESH, sizeof FRESH/sizeof FRESH[0]);

    Beat_Tracker tracker;
    beat_tracker_reset(&tracker);
    int index = 0;
    step(&tracker, "reject_running", index++, 0.0, true, 0.5);
    step(&tracker, "reject_running", index++, 0.5, true, 0.5);
    step(&tracker, "reject_running", index++, NAN, false, 0.0f);
    step(&tracker, "reject_running", index++, INFINITY, false, 0.0f);
    step(&tracker, "reject_running", index++, -INFINITY, false, 0.0f);
    step(&tracker, "reject_running", index++, -1.0e-300, false, 0.0f);
    step(&tracker, "reject_running", index++, 1.0, false, (float)NAN);
    step(&tracker, "reject_running", index++, 1.0, false, (float)INFINITY);
    step(&tracker, "reject_running", index++, 1.0, false, -(float)INFINITY);
    step(&tracker, "reject_running", index++, 1.0, false, -0.1f);
    /* Normal rather than subnormal on purpose: a decimal literal in the
     * subnormal range is a needless bet that both compilers round it the same
     * way, and the thing under test is the sign check. */
    step(&tracker, "reject_running", index++, 1.0, false, -1.0e-30f);
    /* Nothing above touched the state, so this reads as if it came straight
     * after the 0.5 s onset. */
    step(&tracker, "reject_running", index++, 1.0, false, 0.5f);
    step(&tracker, "reject_running", index++, 1.0e18, false, 0.5f);
    step(&tracker, "reject_running", index++, 2.0, false, 0.5f);
    /* Unsuffixed on purpose. Writing this as `3.4028235e38f` made it a *float*
     * literal widened to the double parameter, which is a different number from
     * the same decimal parsed as a double -- and the two harnesses disagreed by
     * 3.4e30 on the very first run. The input columns are echoed so that a drift
     * between the two duplicated generators fails here, in a key column, instead
     * of being blamed on the port. */
    step(&tracker, "reject_running", index++, 1.0e300, false, 0.5f);
}

/*
 * `reset` is the public "forget everything", and it is deliberately *not* the
 * internal restart a discontinuity performs: the restart keeps a credible
 * interval across the gap, reset drops it. Both are dumped here from the same
 * learned state so the difference is a pair of rows rather than a claim.
 */
static void run_reset_versus_seek(void)
{
    Beat_Tracker tracker;
    beat_tracker_reset(&tracker);
    int index = 0;
    for (int beat = 0; beat < 6; ++beat) {
        step(&tracker, "reset_vs_seek", index++, (double)beat*0.6, true, 0.5f);
    }
    /* A forward jump past 0.75 s: new phase reference, tempo survives. */
    step(&tracker, "reset_vs_seek", index++, 30.0, false, 0.0f);
    step(&tracker, "reset_vs_seek", index++, 30.25, false, 0.0f);
    /* Now the explicit reset from the same shape of state. */
    dump_reset(&tracker, "reset_vs_seek", index++);
    step(&tracker, "reset_vs_seek", index++, 30.5, false, 0.0f);
    step(&tracker, "reset_vs_seek", index++, 30.75, false, 0.0f);
}

/*
 * A `false` return with no invalid input.
 *
 * position is 0.99999999999 as a double, which is inside [0, 1); narrowed to a
 * float it becomes exactly 1.0, and the final check refuses it. So the tracker
 * declines a phase it computed itself -- and writes it anyway, which is the
 * difference this case exists to pin.
 *
 * Written as a deliberate case, but it turns out not to be a corner: the grid
 * above reaches the same state 187 times without trying, because accumulated tick
 * drift puts the position a hair under an exact multiple of the interval whenever
 * the tick nearly divides it. `restart_boundary` index 5 hits it too, from the
 * 0.75 s gaps. Neither test suite has a case for it.
 */
static const Input FLOAT_ROUNDS_TO_ONE[] = {
    { 0.0,            0, 0.0f },
    { 0.499999999995, 0, 0.0f },
    { 0.5,            0, 0.0f },
};

int main(void)
{
    run_grid();

    run_case("restart_boundary", RESTART_BOUNDARY,
             sizeof RESTART_BOUNDARY/sizeof RESTART_BOUNDARY[0]);
    run_case("gap_min_boundary", GAP_MIN_BOUNDARY,
             sizeof GAP_MIN_BOUNDARY/sizeof GAP_MIN_BOUNDARY[0]);
    run_case("gap_max_boundary", GAP_MAX_BOUNDARY,
             sizeof GAP_MAX_BOUNDARY/sizeof GAP_MAX_BOUNDARY[0]);
    run_strength_floor();
    run_case("tempo_fold", TEMPO_FOLD,
             sizeof TEMPO_FOLD/sizeof TEMPO_FOLD[0]);
    run_case("weight_transition", WEIGHT_TRANSITION,
             sizeof WEIGHT_TRANSITION/sizeof WEIGHT_TRANSITION[0]);
    run_case("float_rounds_to_one", FLOAT_ROUNDS_TO_ONE,
             sizeof FLOAT_ROUNDS_TO_ONE/sizeof FLOAT_ROUNDS_TO_ONE[0]);
    run_rejections();
    run_reset_versus_seek();

    /*
     * Mechanism divergences, stated rather than quietly excluded. Both are inputs
     * each side cannot express: C takes bare pointers and documents a null tracker
     * or a null out-parameter as a refusal, and Rust takes `&mut self` and returns
     * an enum, so neither is an input it can be handed.
     *
     * There used to be a third entry here claiming the out-of-range write was an
     * oracle quirk the port deliberately did not reproduce. That was wrong -- the
     * C's caller uses the written value -- and writing the claim down is what
     * exposed it. It is now a compared column on every `step` row instead.
     */
    printf("divergence null_tracker c_returns_false\n");
    printf("divergence null_phase_out c_returns_false\n");

    /* Proof the two refusals above are what the oracle actually does, rather
     * than what its header says. Reading the .c is the rule; running it is
     * better. */
    {
        Beat_Tracker tracker;
        beat_tracker_reset(&tracker);
        float phase = 7.0f;
        bool null_tracker = beat_tracker_update(NULL, 0.0, false, 0.0f, &phase);
        bool null_phase = beat_tracker_update(&tracker, 0.0, false, 0.0f, NULL);
        printf("oracle_only null_tracker_returned %d\n", null_tracker ? 1 : 0);
        printf("oracle_only null_phase_returned %d\n", null_phase ? 1 : 0);
        printf("oracle_only phase_untouched_by_null_tracker %s\n", num((double)phase));
    }

    return 0;
}
