/*
 * Differential harness: dumps the *oracle's* timeline view over a wide grid of
 * view states, strip geometries and operation sequences, so the Rust port can be
 * compared against it numerically instead of by property assertion.
 *
 * This compiles `../musializer/src/timeline_view.c` from the frozen C repository
 * unmodified. It reads that tree and writes only into our own `build/`; the
 * oracle is never modified, and its own build directory is never touched.
 *
 * Why this module gets a harness rather than a review: timeline_view is the
 * single seconds<->pixel conversion the whole strip goes through -- the tick
 * ladder, the playhead, the scrubber, the event markers, the lyric blocks and the
 * waveform envelope's per-column bin range all call into it. That is deliberate
 * (`timeline_view.h:6-11`) and it is also why a drift here is invisible: if the
 * view is wrong, every element on the strip is wrong *consistently*, so the strip
 * still photographs as a self-coherent picture.
 *
 * The port's own tests were almost entirely property assertions -- `is_finite()`,
 * `span <= duration + 1e-9`, `span/step >= 2.0` -- which a genuinely wrong
 * formula would survive. `../musializer/tests/test_timeline_view.c` pins 32 exact
 * values, and hand-transcribing those would risk a typo or, worse, a number
 * copied from our own output. A differential comparison cannot be tautological.
 *
 * Everything printed here is generated by plain double arithmetic with explicit
 * evaluation order, duplicated in `timeline_view_dump.rs` on purpose. Two copies
 * of a grid generator is normally a smell; here it is the entire mechanism,
 * because a shared generator could hide the very difference the test looks for.
 * The grid *inputs* are printed alongside the outputs so the two tables are
 * themselves compared: if the duplicated grids ever drift apart, the key columns
 * fail before the value columns do.
 *
 * Build and run through tools/differential_timeline_view.sh.
 */

#include <math.h>
#include <stddef.h>
#include <stdio.h>

#include "timeline_view.h"

/*
 * Seventeen digits after the point, in exponential form. A double round-trips in
 * seventeen significant digits, so printing is not the limiting factor and any
 * delta the comparison reports is arithmetic rather than formatting. Exponential
 * form also keeps a float token from ever looking like an integer to the
 * comparison script, which is how it knows which columns to compare exactly.
 *
 * Non-finite values get a *label* instead of `nan`/`inf`. That is not cosmetic:
 * `nan` and `inf` both parse as floats in Python, and `abs(nan - nan) > tol` is
 * False, so a column of them would pass unconditionally -- a silent hole the
 * project has already been bitten by once. These labels contain no digits and no
 * spelling `float()` accepts, so they fall through to the exact-string branch and
 * a NaN where a number belongs fails loudly. C spells them the same way the Rust
 * side does because both sides spell them by hand.
 */
#define FLOAT_FMT "%.17e"

/*
 * A rotating pool so several numbers can appear in one printf. Argument
 * evaluation order is unspecified in C, which is exactly why each call must get
 * its own buffer rather than share one; no record below prints more than eight
 * numbers.
 */
#define NUM_BUF_COUNT 12
static char num_bufs[NUM_BUF_COUNT][48];
static int num_buf_next = 0;

static const char *num(double value)
{
    if (isnan(value)) return "not_a_number";
    if (isinf(value)) return value > 0.0 ? "positive_infinity" : "negative_infinity";
    char *buf = num_bufs[num_buf_next];
    num_buf_next = (num_buf_next + 1)%NUM_BUF_COUNT;
    snprintf(buf, sizeof num_bufs[0], FLOAT_FMT, value);
    return buf;
}

/* ------------------------------------------------------------------------- *
 * The grid. Duplicated in timeline_view_dump.rs, value for value.
 * ------------------------------------------------------------------------- */

/*
 * Durations for the clamp sweep. Zero, negative and non-finite are the "there is
 * no timeline" family; 1e-9 through 0.2500000001 straddle the span floor from
 * both sides, because a floor that does not yield to a very short track puts the
 * window past the end of the material (`timeline_view.c:11-17`).
 */
static const double durations_a[] = {
    0.0, -1.0, -240.0, NAN, INFINITY, -INFINITY, 1.0e-9, 0.05, 0.1, 0.2499,
    0.25, 0.2500000001, 1.0, 3.7, 40.0, 90.0, 240.0, 600.0, 3600.0, 12345.678,
};

/*
 * Raw view states fed straight to clamp without going through a mutator, which
 * is how a hot-reloaded layout or a caller that did its own arithmetic reaches
 * it. The non-finite ones exercise the recovery path (`timeline_view.c:36-41`),
 * which is the branch a property assertion is least able to distinguish from
 * "happened to be legal already".
 */
static const struct { double start; double span; } states_a[] = {
    {0.0, 0.0}, {0.0, 240.0}, {0.0, -5.0}, {0.0, 0.25}, {0.0, 0.1},
    {-30.0, 60.0}, {30.0, 60.0}, {230.0, 60.0}, {1000.0, 60.0},
    {0.0, 1.0e-12}, {0.0, 1.0e9}, {120.0, 1.0e9},
    {NAN, 60.0}, {0.0, NAN}, {NAN, NAN}, {INFINITY, 60.0}, {0.0, INFINITY},
    {-INFINITY, 60.0}, {0.0, -INFINITY}, {239.9999999, 0.25},
};

/* Durations for the conversion sweep, including the unusable ones so
 * seconds_at's `usable_duration` early return is covered. */
static const double durations_b[] = {-1.0, 0.0, 0.1, 1.0, 40.0, 240.0, 3600.0};

/*
 * Strip geometries. A one-pixel and a two-pixel strip because the division by
 * width is where a narrow strip stops being representable; a negative left
 * because the strip is scrolled inside a panel; zero and negative width because
 * a panel can be laid out before it has been sized; non-finite because a NaN
 * that reaches a pixel conversion poisons every later frame.
 */
static const struct { double left; double width; } geoms_b[] = {
    {0.0, 1.0}, {0.0, 2.0}, {12.0, 1200.0}, {-40.0, 900.0}, {7.5, 1919.0},
    {12.0, 0.0}, {12.0, -5.0}, {12.0, NAN}, {NAN, 900.0},
};

/* Moments to map onto the strip, deliberately including ones outside the window
 * and outside the track: x_at must report an off-screen edge honestly rather than
 * pre-clamping it (`timeline_view.h:58-61`). */
static const double seconds_b[] = {
    -10.0, 0.0, 1.0e-3, 0.05, 0.5, 3.7, 60.0, 120.0, 239.999, 240.0, 5000.0,
    NAN, INFINITY, -INFINITY,
};

/* Pixel positions, in absolute coordinates rather than relative to `left`, so a
 * drag that leaves the strip is covered for every geometry. */
static const double xs_b[] = {
    -4000.0, -1.0, 0.0, 1.0, 12.0, 300.0, 611.5, 1212.0, 9000.0,
    NAN, INFINITY, -INFINITY,
};

static const double durations_c[] = {-1.0, 0.0, 0.1, 0.25, 1.0, 40.0, 240.0, 3600.0};

/*
 * Zoom factors. 1e-9 and 1e12 hit the whole-track ceiling and the span floor in
 * one step; 0.9/1.0/1.1 sit either side of inert; 0.0, -2.0 and the non-finite
 * ones are the caller-bug family the C ignores outright.
 */
static const double factors_c[] = {
    0.0, -2.0, NAN, INFINITY, 1.0e-9, 0.01, 0.5, 0.9, 1.0, 1.1, 2.0, 4.0, 64.0,
    1.0e12,
};

/*
 * Anchors. The interesting ones are outside the current window and outside the
 * track entirely, because that is the case the header says is only violated when
 * honouring it would push the window off an end (`timeline_view.h:44-45`). A
 * non-finite anchor is not a caller bug but a request to zoom on the middle.
 */
static const double anchors_c[] = {
    0.0, 0.05, 3.7, 20.0, 90.0, 120.0, 240.0, -50.0, 1.0e6, NAN, INFINITY,
};

/*
 * Reveal targets and pan deltas, sharing one table because both are "a signed
 * amount of seconds the caller believes in". Both signs of a huge value are here
 * because reveal's two branches are asymmetric in the source -- one subtracts the
 * margin, the other subtracts the span and adds it back (`timeline_view.c:106-110`)
 * -- and a margin applied to the wrong side still keeps the moment on screen.
 */
static const double reveals_c[] = {
    -1.0e9, -50.0, -0.001, 0.0, 0.05, 3.7, 20.0, 60.0, 120.0, 239.9, 240.0,
    1.0e6, NAN, INFINITY, -INFINITY,
};

/* The tick ladder, duplicated from timeline_view.c so the boundary probes can be
 * generated from it. If the port's ladder differs, the `tick` rows disagree. */
static const double ladder[] = {
    0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0, 10.0,
    15.0, 30.0, 60.0, 120.0, 300.0, 600.0,
};

/* Geometry used for the zoom and chain sections, where the point is the state
 * rather than the strip: the anchor's pixel position is what wheel zoom depends
 * on staying put, so it has to be measured somewhere. */
#define STRIP_LEFT 12.0
#define STRIP_WIDTH 1200.0

/* ------------------------------------------------------------------------- *
 * View constructors. Each one is a scripted sequence, so a state that only
 * exists after two operations is reachable.
 * ------------------------------------------------------------------------- */

/* Nine starting states for the conversion sweep. Kinds 5 to 8 are deliberately
 * *not* clamped: x_at and seconds_at have their own guards and must survive a
 * state no mutator would have produced. */
static Timeline_View probe_view(int kind, double duration)
{
    Timeline_View view = {0.0, 0.0};
    switch (kind) {
    case 0:
        timeline_view_reset(&view, duration);
        break;
    case 1:
        timeline_view_reset(&view, duration);
        timeline_view_zoom(&view, duration, 4.0, 90.0);
        break;
    case 2:
        timeline_view_reset(&view, duration);
        timeline_view_zoom(&view, duration, 12.0, 77.0);
        break;
    case 3:
        timeline_view_reset(&view, duration);
        timeline_view_zoom(&view, duration, 64.0, 200.0);
        timeline_view_pan(&view, duration, 30.0);
        break;
    case 4:
        timeline_view_reset(&view, duration);
        timeline_view_zoom(&view, duration, 1000.0, 10.0);
        break;
    case 5:
        view.start_seconds = 0.0;
        view.span_seconds = NAN;
        break;
    case 6:
        view.start_seconds = 5.0;
        view.span_seconds = 0.0;
        break;
    case 7:
        view.start_seconds = NAN;
        view.span_seconds = 60.0;
        break;
    default:
        view.start_seconds = -15.0;
        view.span_seconds = -3.0;
        break;
    }
    return view;
}

/* Four starting states for the zoom sweep: whole, mid-track, near the floor at
 * the head, and pinned at the tail. */
static Timeline_View base_view(int kind, double duration)
{
    Timeline_View view = {0.0, 0.0};
    timeline_view_reset(&view, duration);
    switch (kind) {
    case 1:
        timeline_view_zoom(&view, duration, 4.0, 90.0);
        break;
    case 2:
        timeline_view_zoom(&view, duration, 200.0, 5.0);
        break;
    case 3:
        timeline_view_zoom(&view, duration, 8.0, duration);
        break;
    default:
        break;
    }
    return view;
}

/* ------------------------------------------------------------------------- *
 * Sections
 * ------------------------------------------------------------------------- */

/* The two tuning constants, pinned directly. A harness that compares only
 * derived numbers would report a nudged floor as dozens of unexplained deltas;
 * this row names it. */
static void dump_constants(void)
{
    printf("constant min_span %s\n", num(TIMELINE_VIEW_MIN_SPAN_SECONDS));
    printf("constant reveal_margin %s\n", num(TIMELINE_VIEW_REVEAL_MARGIN));
}

static void dump_reset_and_clamp(void)
{
    size_t duration_count = sizeof durations_a/sizeof durations_a[0];
    size_t state_count = sizeof states_a/sizeof states_a[0];

    for (size_t d = 0; d < duration_count; ++d) {
        Timeline_View view = {0.0, 0.0};
        timeline_view_reset(&view, durations_a[d]);
        printf("reset %s %s %s %d\n", num(durations_a[d]),
               num(view.start_seconds), num(view.span_seconds),
               timeline_view_is_whole(&view, durations_a[d]) ? 1 : 0);
    }

    for (size_t d = 0; d < duration_count; ++d) {
        for (size_t s = 0; s < state_count; ++s) {
            Timeline_View view;
            view.start_seconds = states_a[s].start;
            view.span_seconds = states_a[s].span;
            /* is_whole *before* the clamp, because the non-finite-span branch
             * answers true and is unreachable once clamp has run. */
            int raw_whole = timeline_view_is_whole(&view, durations_a[d]) ? 1 : 0;
            timeline_view_clamp(&view, durations_a[d]);
            printf("clamp %s %s %s %d %s %s %d\n",
                   num(durations_a[d]), num(states_a[s].start),
                   num(states_a[s].span), raw_whole,
                   num(view.start_seconds), num(view.span_seconds),
                   timeline_view_is_whole(&view, durations_a[d]) ? 1 : 0);
        }
    }
}

static void dump_conversions(void)
{
    size_t duration_count = sizeof durations_b/sizeof durations_b[0];
    size_t geom_count = sizeof geoms_b/sizeof geoms_b[0];
    size_t seconds_count = sizeof seconds_b/sizeof seconds_b[0];
    size_t x_count = sizeof xs_b/sizeof xs_b[0];

    for (size_t d = 0; d < duration_count; ++d) {
        double duration = durations_b[d];
        for (int kind = 0; kind < 9; ++kind) {
            Timeline_View view = probe_view(kind, duration);
            /* The state itself, so a conversion difference can be told apart
             * from a difference in how the state was reached. */
            printf("probe %s %d %s %s\n", num(duration), kind,
                   num(view.start_seconds), num(view.span_seconds));
            for (size_t g = 0; g < geom_count; ++g) {
                double left = geoms_b[g].left;
                double width = geoms_b[g].width;
                printf("spp %s %d %s %s\n", num(duration), kind, num(width),
                       num(timeline_view_seconds_per_pixel(&view, width)));
                for (size_t i = 0; i < seconds_count; ++i) {
                    printf("x_at %s %d %s %s %s %s\n", num(duration), kind,
                           num(left), num(width), num(seconds_b[i]),
                           num(timeline_view_x_at(&view, seconds_b[i], left,
                                                  width)));
                }
                for (size_t i = 0; i < x_count; ++i) {
                    printf("seconds_at %s %d %s %s %s %s\n", num(duration), kind,
                           num(left), num(width), num(xs_b[i]),
                           num(timeline_view_seconds_at(&view, xs_b[i], left,
                                                        width, duration)));
                }
                /* The round trip the C's own test checks at 1e-6
                 * (`tests/test_timeline_view.c:151-160`), here at every eleventh
                 * of the strip for every geometry rather than one zoom level. */
                for (int f = 0; f <= 10; ++f) {
                    double fraction = (double)f/10.0;
                    double x = left + width*fraction;
                    double seconds = timeline_view_seconds_at(&view, x, left,
                                                              width, duration);
                    double back = timeline_view_x_at(&view, seconds, left, width);
                    printf("round_trip %s %d %s %s %s %s %s\n", num(duration),
                           kind, num(left), num(width), num(fraction),
                           num(seconds), num(back));
                }
            }
        }
    }
}

static void dump_zoom(void)
{
    size_t duration_count = sizeof durations_c/sizeof durations_c[0];
    size_t factor_count = sizeof factors_c/sizeof factors_c[0];
    size_t anchor_count = sizeof anchors_c/sizeof anchors_c[0];

    for (size_t d = 0; d < duration_count; ++d) {
        double duration = durations_c[d];
        for (int kind = 0; kind < 4; ++kind) {
            for (size_t f = 0; f < factor_count; ++f) {
                for (size_t a = 0; a < anchor_count; ++a) {
                    Timeline_View view = base_view(kind, duration);
                    /* Where the anchor sat before the zoom, and where it sits
                     * after. Wheel zoom feeling attached to the pointer is
                     * exactly these two numbers agreeing, and it is the property
                     * an off-by-a-fraction formulation still looks plausible
                     * without. */
                    double before = timeline_view_x_at(&view, anchors_c[a],
                                                       STRIP_LEFT, STRIP_WIDTH);
                    timeline_view_zoom(&view, duration, factors_c[f],
                                       anchors_c[a]);
                    double after = timeline_view_x_at(&view, anchors_c[a],
                                                      STRIP_LEFT, STRIP_WIDTH);
                    printf("zoom %s %d %s %s %s %s %s %d %s\n", num(duration),
                           kind, num(factors_c[f]), num(anchors_c[a]),
                           num(before), num(view.start_seconds),
                           num(view.span_seconds),
                           timeline_view_is_whole(&view, duration) ? 1 : 0,
                           num(after));
                }
            }
        }
    }
}

/*
 * reveal and pan get their own sweep rather than only appearing inside the
 * chains, because between them they are the whole of follow-playback and of
 * dragging the strip, and a margin applied to the wrong edge still keeps the
 * moment on screen -- which is all a property assertion can check.
 */
static void dump_reveal_and_pan(void)
{
    size_t duration_count = sizeof durations_c/sizeof durations_c[0];
    size_t amount_count = sizeof reveals_c/sizeof reveals_c[0];

    for (size_t d = 0; d < duration_count; ++d) {
        double duration = durations_c[d];
        for (int kind = 0; kind < 4; ++kind) {
            for (size_t i = 0; i < amount_count; ++i) {
                Timeline_View view = base_view(kind, duration);
                timeline_view_reveal(&view, duration, reveals_c[i]);
                printf("reveal %s %d %s %s %s %d\n", num(duration), kind,
                       num(reveals_c[i]), num(view.start_seconds),
                       num(view.span_seconds),
                       timeline_view_is_whole(&view, duration) ? 1 : 0);

                Timeline_View panned = base_view(kind, duration);
                timeline_view_pan(&panned, duration, reveals_c[i]);
                printf("pan %s %d %s %s %s %d\n", num(duration), kind,
                       num(reveals_c[i]), num(panned.start_seconds),
                       num(panned.span_seconds),
                       timeline_view_is_whole(&panned, duration) ? 1 : 0);
            }
        }
    }
}

/*
 * Follow-playback as it is actually used: reveal called once per frame while the
 * playhead advances across the whole track. This is the only shape in which the
 * margin's job -- not re-centring on every frame at the boundary
 * (`timeline_view.h:23-25`) -- is observable, because it depends on the *sequence*
 * of calls leaving the view alone until the playhead reaches the edge.
 */
static void dump_follow(void)
{
    size_t duration_count = sizeof durations_c/sizeof durations_c[0];
    for (size_t d = 0; d < duration_count; ++d) {
        double duration = durations_c[d];
        for (int kind = 1; kind < 3; ++kind) {
            Timeline_View view = base_view(kind, duration);
            for (int step = 0; step <= 97; ++step) {
                double playhead = duration*((double)step/97.0);
                timeline_view_reveal(&view, duration, playhead);
                printf("follow %s %d %d %s %s %s %d %s\n", num(duration), kind,
                       step, num(playhead), num(view.start_seconds),
                       num(view.span_seconds),
                       timeline_view_is_whole(&view, duration) ? 1 : 0,
                       num(timeline_view_x_at(&view, playhead, STRIP_LEFT,
                                              STRIP_WIDTH)));
            }
        }
    }
}

/* ------------------------------------------------------------------------- *
 * Sequences. The view is stateful, so a single-call harness would miss an error
 * that only appears after two operations -- a clamp that quietly shrinks the
 * span, for instance, is invisible until the next pan reveals that the window
 * got smaller.
 * ------------------------------------------------------------------------- */

enum { OP_RESET, OP_CLAMP, OP_ZOOM, OP_PAN, OP_REVEAL };

static const char *op_names[] = {"reset", "clamp", "zoom", "pan", "reveal"};

struct Op { int kind; double a; double b; };

#define MAX_OPS 10

static const struct Chain {
    const char *name;
    size_t count;
    struct Op ops[MAX_OPS];
} chains[] = {
    {"zoom_in_then_out", 6, {
        {OP_ZOOM, 2.0, 120.0}, {OP_ZOOM, 2.0, 120.0}, {OP_ZOOM, 2.0, 120.0},
        {OP_ZOOM, 0.5, 120.0}, {OP_ZOOM, 0.5, 120.0}, {OP_ZOOM, 0.5, 120.0},
    }},
    {"zoom_then_pan_tail", 5, {
        {OP_ZOOM, 8.0, 0.0}, {OP_PAN, 1000.0, 0.0}, {OP_PAN, -3.0, 0.0},
        {OP_ZOOM, 2.0, NAN}, {OP_PAN, -1.0e9, 0.0},
    }},
    {"reveal_follow", 7, {
        {OP_ZOOM, 16.0, 0.0}, {OP_REVEAL, 10.0, 0.0}, {OP_REVEAL, 20.0, 0.0},
        {OP_REVEAL, 30.0, 0.0}, {OP_REVEAL, 200.0, 0.0}, {OP_REVEAL, 0.0, 0.0},
        {OP_REVEAL, NAN, 0.0},
    }},
    {"floor_walk", 8, {
        {OP_ZOOM, 3.0, 60.0}, {OP_ZOOM, 3.0, 60.0}, {OP_ZOOM, 3.0, 60.0},
        {OP_ZOOM, 3.0, 60.0}, {OP_ZOOM, 3.0, 60.0}, {OP_ZOOM, 0.7, 60.0},
        {OP_ZOOM, 0.7, 60.0}, {OP_ZOOM, 0.7, 60.0},
    }},
    {"clamp_between", 6, {
        {OP_ZOOM, 6.0, 50.0}, {OP_CLAMP, 0.0, 0.0}, {OP_PAN, 7.0, 0.0},
        {OP_CLAMP, 0.0, 0.0}, {OP_REVEAL, 51.0, 0.0}, {OP_CLAMP, 0.0, 0.0},
    }},
    {"nan_poison_recovery", 6, {
        {OP_ZOOM, 4.0, 60.0}, {OP_PAN, NAN, 0.0}, {OP_ZOOM, NAN, 60.0},
        {OP_REVEAL, INFINITY, 0.0}, {OP_CLAMP, 0.0, 0.0}, {OP_ZOOM, 2.0, 60.0},
    }},
    {"reset_midway", 4, {
        {OP_ZOOM, 32.0, 100.0}, {OP_PAN, 50.0, 0.0}, {OP_RESET, 0.0, 0.0},
        {OP_ZOOM, 4.0, 10.0},
    }},
    {"tail_anchor_zoom", 4, {
        {OP_ZOOM, 4.0, 239.9}, {OP_ZOOM, 4.0, 239.9}, {OP_ZOOM, 4.0, 239.9},
        {OP_ZOOM, 0.25, 239.9},
    }},
    {"head_anchor_zoom", 4, {
        {OP_ZOOM, 4.0, 0.0}, {OP_ZOOM, 4.0, 0.0}, {OP_ZOOM, 4.0, 0.0},
        {OP_ZOOM, 0.25, 0.0},
    }},
    {"negative_anchor", 4, {
        {OP_ZOOM, 4.0, -100.0}, {OP_ZOOM, 4.0, -100.0}, {OP_REVEAL, -5.0, 0.0},
        {OP_PAN, -2.0, 0.0},
    }},
    {"whole_track_ceiling", 4, {
        {OP_ZOOM, 0.1, 120.0}, {OP_ZOOM, 0.1, 120.0}, {OP_ZOOM, 1.0e-9, 120.0},
        {OP_REVEAL, 120.0, 0.0},
    }},
    /* Panning must never change how much you can see. A clamp written as "shrink
     * the span to fit" keeps the invariant and silently zooms
     * (`tests/test_timeline_view.c:121-123`), which is only visible in a chain. */
    {"pan_never_zooms", 5, {
        {OP_ZOOM, 5.0, 77.0}, {OP_PAN, 1.0e-3, 0.0}, {OP_PAN, -1.0e-3, 0.0},
        {OP_PAN, 1.0e6, 0.0}, {OP_PAN, -1.0e6, 0.0},
    }},
};

static const double durations_d[] = {0.0, 0.1, 3.7, 240.0};

static void apply_op(Timeline_View *view, double duration, const struct Op *op)
{
    switch (op->kind) {
    case OP_RESET:  timeline_view_reset(view, duration); break;
    case OP_CLAMP:  timeline_view_clamp(view, duration); break;
    case OP_ZOOM:   timeline_view_zoom(view, duration, op->a, op->b); break;
    case OP_PAN:    timeline_view_pan(view, duration, op->a); break;
    default:        timeline_view_reveal(view, duration, op->a); break;
    }
}

static void dump_chains(void)
{
    size_t chain_count = sizeof chains/sizeof chains[0];
    size_t duration_count = sizeof durations_d/sizeof durations_d[0];

    for (size_t c = 0; c < chain_count; ++c) {
        for (size_t d = 0; d < duration_count; ++d) {
            double duration = durations_d[d];
            Timeline_View view = {0.0, 0.0};
            timeline_view_reset(&view, duration);
            for (size_t s = 0; s < chains[c].count; ++s) {
                apply_op(&view, duration, &chains[c].ops[s]);
                /* State plus the three derived quantities the strip actually
                 * draws from, so a state that is legal but shifted shows up. */
                printf("chain %s %s %zu %s %s %s %d %s %s %s\n",
                       chains[c].name, num(duration), s,
                       op_names[chains[c].ops[s].kind],
                       num(view.start_seconds), num(view.span_seconds),
                       timeline_view_is_whole(&view, duration) ? 1 : 0,
                       num(timeline_view_seconds_per_pixel(&view, STRIP_WIDTH)),
                       num(timeline_view_x_at(&view, 0.0, STRIP_LEFT, STRIP_WIDTH)),
                       num(timeline_view_x_at(&view, duration, STRIP_LEFT,
                                              STRIP_WIDTH)));
            }
        }
    }
}

/*
 * The tick ladder is a step function, so the only way to catch a rung being off
 * by one is to sweep densely enough to land on both sides of every boundary. The
 * boundary is at span = 8*rung (`timeline_view.c:159-162`), so each rung is
 * probed exactly on it and a part in 1e12 either side, and then the whole range
 * is swept geometrically.
 */
static void dump_tick_step(void)
{
    size_t rung_count = sizeof ladder/sizeof ladder[0];
    for (size_t i = 0; i < rung_count; ++i) {
        double boundary = ladder[i]*8.0;
        double probes[] = {
            boundary, boundary*(1.0 - 1.0e-12), boundary*(1.0 + 1.0e-12),
            ladder[i], ladder[i]/8.0,
        };
        for (size_t p = 0; p < sizeof probes/sizeof probes[0]; ++p) {
            printf("tick %s %s\n", num(probes[p]),
                   num(timeline_view_tick_step(probes[p])));
        }
    }

    for (double span = 1.0e-4; span < 1.0e5; span *= 1.02) {
        printf("tick %s %s\n", num(span), num(timeline_view_tick_step(span)));
    }

    /* The last entry is the smallest positive subnormal, spelled as `5e-324` on
     * both sides because that is the shortest literal that rounds to it: writing
     * its exact value out in full is more digits than a double distinguishes. */
    static const double degenerate[] = {
        0.0, -1.0, -1.0e300, NAN, INFINITY, -INFINITY, 1.0e-300, 1.0e300,
        5.0e-324,
    };
    for (size_t i = 0; i < sizeof degenerate/sizeof degenerate[0]; ++i) {
        printf("tick %s %s\n", num(degenerate[i]),
               num(timeline_view_tick_step(degenerate[i])));
    }
}

/*
 * Divergences in mechanism, recorded rather than hidden. The C takes a bare
 * `Timeline_View *` and documents a null one as inert; Rust takes `&self` and
 * `&mut self`, so a null view is not a case it can refuse -- it is a case it
 * cannot express. Both halves print their side of each pair and the driver
 * asserts the pair, which keeps the difference visible instead of silently
 * excluded. The C side really does make the calls, so these rows are measured
 * behaviour rather than a restated comment.
 */
static void dump_divergences(void)
{
    double x = timeline_view_x_at(NULL, 30.0, STRIP_LEFT, STRIP_WIDTH);
    printf("divergence null_view_x_at %s\n",
           x == STRIP_LEFT ? "c_returns_left" : "c_returns_other");
    double seconds = timeline_view_seconds_at(NULL, 300.0, STRIP_LEFT,
                                              STRIP_WIDTH, 240.0);
    printf("divergence null_view_seconds_at %s\n",
           seconds == 0.0 ? "c_returns_zero" : "c_returns_other");
    printf("divergence null_view_is_whole %s\n",
           timeline_view_is_whole(NULL, 240.0) ? "c_returns_true" : "c_returns_false");
    printf("divergence null_view_seconds_per_pixel %s\n",
           timeline_view_seconds_per_pixel(NULL, STRIP_WIDTH) == 0.0 ?
               "c_returns_zero" : "c_returns_other");
    /* The mutators have nothing observable to report -- a null view is exactly
     * the state they cannot write to -- so this row asserts only that they
     * return rather than fault. */
    timeline_view_reset(NULL, 240.0);
    timeline_view_clamp(NULL, 240.0);
    timeline_view_zoom(NULL, 240.0, 2.0, 120.0);
    timeline_view_pan(NULL, 240.0, 5.0);
    timeline_view_reveal(NULL, 240.0, 5.0);
    printf("divergence null_view_mutators c_no_op\n");
}

int main(void)
{
    dump_constants();
    dump_reset_and_clamp();
    dump_conversions();
    dump_zoom();
    dump_reveal_and_pan();
    dump_follow();
    dump_chains();
    dump_tick_step();
    dump_divergences();
    return 0;
}
