#!/bin/sh
#
# Installs a per-user application launcher for Rusty Musializer.
#
# Adapted from ../musializer/tools/install-linux-launcher.sh. Two differences that
# matter:
#
#   * it builds with cargo instead of nob, and
#   * it uses the application id `rusty-musializer`, not
#     `io.github.tsoding.musializer`, so it installs *alongside* the C launcher
#     rather than replacing it. Both can be in the menu at once, which is the
#     point while the C build is still the parity oracle.
#
# Per-user only: everything lands under $XDG_DATA_HOME and $XDG_BIN_HOME. Nothing
# is written outside the user's home, and no step needs root.

set -eu

PROJECT_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
APP_ID=rusty-musializer
DATA_HOME=${XDG_DATA_HOME:-"$HOME/.local/share"}
BIN_HOME=${XDG_BIN_HOME:-"$HOME/.local/bin"}
DESKTOP_FILE="$DATA_HOME/applications/$APP_ID.desktop"
ICON_DIR="$DATA_HOME/icons/hicolor"
MIME_FILE="$DATA_HOME/mime/packages/$APP_ID.xml"
LAUNCHER_FILE="$BIN_HOME/$APP_ID"
DESKTOP_TEMPLATE="$PROJECT_ROOT/packaging/linux/$APP_ID.desktop.in"
MIME_TEMPLATE="$PROJECT_ROOT/packaging/linux/$APP_ID.xml"
LAUNCHER_TEMPLATE="$PROJECT_ROOT/tools/$APP_ID-launcher"

# The sizes tools/make_rust_logo.py produces. 256 is what a menu actually shows;
# the rest keep the icon crisp in a panel, a taskbar and a file dialog.
ICON_SIZES="16 32 48 64 128 256"

usage()
{
    printf '%s\n' \
        "Usage: $0 [--install|--uninstall] [--skip-build] [--no-refresh]" \
        "" \
        "Installs a per-user application launcher for Rusty Musializer, alongside" \
        "(not replacing) the C project's entry. Installation builds the release" \
        "executable unless --skip-build is supplied. --no-refresh skips the" \
        "desktop-menu cache refresh, which is useful in containers and tests."
}

mode=install
build=yes
refresh=yes
while [ "$#" -gt 0 ]; do
    case "$1" in
        --install) mode=install ;;
        --uninstall) mode=uninstall ;;
        --skip-build) build=no ;;
        --no-refresh) refresh=no ;;
        --help|-h) usage; exit 0 ;;
        *) printf '%s\n' "Unknown option: $1" >&2; usage >&2; exit 2 ;;
    esac
    shift
done

refresh_desktop_database()
{
    [ "$refresh" = yes ] || return 0
    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database "$DATA_HOME/applications" >/dev/null 2>&1 || true
    fi
    if command -v gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -q -t "$ICON_DIR" >/dev/null 2>&1 || true
    fi
    if command -v update-mime-database >/dev/null 2>&1; then
        update-mime-database "$DATA_HOME/mime" >/dev/null 2>&1 || true
    fi
    # KDE keeps its own menu cache; without this the entry can take a session to
    # appear. kbuildsycoca6 on Plasma 6, 5 on Plasma 5.
    if command -v kbuildsycoca6 >/dev/null 2>&1; then
        kbuildsycoca6 >/dev/null 2>&1 || true
    elif command -v kbuildsycoca5 >/dev/null 2>&1; then
        kbuildsycoca5 >/dev/null 2>&1 || true
    fi
}

if [ "$mode" = uninstall ]; then
    rm -f "$DESKTOP_FILE" "$MIME_FILE" "$LAUNCHER_FILE"
    for size in $ICON_SIZES; do
        rm -f "$ICON_DIR/${size}x${size}/apps/$APP_ID.png"
    done
    rm -f "$ICON_DIR/scalable/apps/$APP_ID.svg"
    refresh_desktop_database
    printf '%s\n' "Removed the Rusty Musializer application launcher."
    printf '%s\n' "The C project's own entry, if installed, was left alone."
    exit 0
fi

if [ "$(uname -s)" != Linux ]; then
    printf '%s\n' "This installer supports Linux desktop environments only." >&2
    exit 1
fi

APP_RELATIVE=target/release/musializer
APP_BINARY="$PROJECT_ROOT/$APP_RELATIVE"

for required_file in "$DESKTOP_TEMPLATE" "$MIME_TEMPLATE" "$LAUNCHER_TEMPLATE" \
                     "$PROJECT_ROOT/resources/logo/logo-256.png" \
                     "$PROJECT_ROOT/resources/logo/logo.svg"; do
    if [ ! -f "$required_file" ]; then
        printf '%s\n' "Required launcher asset is missing: $required_file" >&2
        printf '%s\n' "Icons are generated by tools/make_rust_logo.py." >&2
        exit 1
    fi
done

if [ "$build" = yes ]; then
    if ! command -v cargo >/dev/null 2>&1; then
        printf '%s\n' "cargo was not found in PATH." >&2
        exit 1
    fi
    (cd "$PROJECT_ROOT" && cargo build --release)
elif [ ! -x "$APP_BINARY" ]; then
    printf '%s\n' "--skip-build was requested, but $APP_BINARY does not exist." >&2
    exit 1
fi
if [ ! -x "$APP_BINARY" ]; then
    printf '%s\n' "The release build completed without producing $APP_BINARY." >&2
    exit 1
fi

mkdir -p \
    "$DATA_HOME/applications" \
    "$DATA_HOME/mime/packages" \
    "$ICON_DIR/scalable/apps" \
    "$BIN_HOME"
for size in $ICON_SIZES; do
    mkdir -p "$ICON_DIR/${size}x${size}/apps"
done

# Shell single-quote escaping is needed for the generated launcher's embedded
# project root. Desktop Exec quoting has its own escaping rules. Both are inherited
# from the C installer, which had already paid for getting this wrong.
escape_sed_replacement()
{
    printf '%s' "$1" | sed 's/[\\&|]/\\&/g'
}

project_root_shell=$(printf '%s' "$PROJECT_ROOT" | sed "s/'/'\\\\''/g")
project_root_shell=$(escape_sed_replacement "'$project_root_shell'")
project_root_desktop=$(printf '%s' "$PROJECT_ROOT" | sed 's/[\\`$\"]/\\\\&/g')
project_root_desktop=$(escape_sed_replacement "$project_root_desktop")
launcher_desktop=$(printf '%s' "$LAUNCHER_FILE" | sed 's/[\\`$\"]/\\\\&/g')
launcher_desktop=$(escape_sed_replacement "$launcher_desktop")

temp_dir=$(mktemp -d)
launcher_tmp="$temp_dir/$APP_ID"
desktop_tmp="$temp_dir/$APP_ID.desktop"
trap 'rm -rf "$temp_dir"' EXIT HUP INT TERM

sed "s|@PROJECT_ROOT_SHELL@|$project_root_shell|g" \
    "$LAUNCHER_TEMPLATE" | \
    sed "s|@APP_RELATIVE@|$APP_RELATIVE|g" >"$launcher_tmp"
sed \
    -e "s|@LAUNCHER@|$launcher_desktop|g" \
    -e "s|@PROJECT_ROOT@|$project_root_desktop|g" \
    "$DESKTOP_TEMPLATE" >"$desktop_tmp"

# Fail the install rather than write a malformed entry: a bad .desktop file is
# ignored silently by the menu, which is indistinguishable from "nothing happened".
if command -v desktop-file-validate >/dev/null 2>&1; then
    desktop-file-validate "$desktop_tmp"
fi

install -m 0755 "$launcher_tmp" "$LAUNCHER_FILE"
install -m 0644 "$desktop_tmp" "$DESKTOP_FILE"
for size in $ICON_SIZES; do
    install -m 0644 "$PROJECT_ROOT/resources/logo/logo-$size.png" \
        "$ICON_DIR/${size}x${size}/apps/$APP_ID.png"
done
install -m 0644 "$PROJECT_ROOT/resources/logo/logo.svg" \
    "$ICON_DIR/scalable/apps/$APP_ID.svg"
install -m 0644 "$MIME_TEMPLATE" "$MIME_FILE"
refresh_desktop_database

printf '%s\n' \
    "Rusty Musializer is installed in your application menu." \
    "Launcher:      $LAUNCHER_FILE" \
    "Desktop entry: $DESKTOP_FILE" \
    "Icons:         $ICON_DIR/{16x16,...,256x256}/apps/$APP_ID.png, scalable/apps/$APP_ID.svg" \
    "Project type:  $MIME_FILE" \
    "Log:           ${XDG_STATE_HOME:-$HOME/.local/state}/rusty-musializer/launcher.log"

if [ ! -f "$DATA_HOME/applications/io.github.tsoding.musializer.desktop" ]; then
    printf '%s\n' \
        "" \
        "Note: the C project's launcher is not installed, so .musi files will show" \
        "a generic document icon. This entry deliberately does not claim that icon;" \
        "see packaging/linux/$APP_ID.xml for why."
fi
